-- ==============================================
-- CREATE INDEXES FOR POST
-- ==============================================

CREATE INDEX IF NOT EXISTS IDX_POST_USER_ID
    ON POST_MANAGEMENT.POST(USER_ID);

-- ==============================================
-- CREATE INDEXES FOR REACT
-- ==============================================
CREATE INDEX IF NOT EXISTS IDX_REACT_USER_ID
    ON POST_MANAGEMENT.REACT(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_REACT_POST_ID
    ON POST_MANAGEMENT.REACT(POST_ID);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_REACT_USER_ID_POST_ID
    ON POST_MANAGEMENT.REACT(USER_ID, POST_ID);

-- ==============================================
-- CREATE INDEXES FOR COMMENT
-- ==============================================
CREATE INDEX IF NOT EXISTS IDX_COMMENT_USER_ID
    ON POST_MANAGEMENT.COMMENT(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_COMMENT_POST_ID
    ON POST_MANAGEMENT.COMMENT(POST_ID);

CREATE INDEX IF NOT EXISTS IDX_COMMENT_USER_ID_POST_ID
    ON POST_MANAGEMENT.COMMENT(USER_ID, POST_ID);

CREATE INDEX IF NOT EXISTS IDX_COMMENT_PARENT_COMMENT_ID_POST_ID
    ON POST_MANAGEMENT.COMMENT(PARENT_COMMENT_ID, POST_ID);

-- ==============================================
-- CREATE INDEXES FOR FOLLOW
-- ==============================================
CREATE UNIQUE INDEX IF NOT EXISTS IDX_FOLLOW_USER_ID
    ON FOLLOW_MANAGEMENT.FOLLOWING(USER_ID);