-- ==============================================
-- CREATE INDEXES FOR POSITION
-- ==============================================

CREATE INDEX IF NOT EXISTS IDX_POSITION_INDUSTRY_ID
    ON BASIC_DATA.POSITION(INDUSTRY_ID);

-- ==============================================
-- CREATE INDEXES FOR USER
-- ==============================================
CREATE INDEX IF NOT EXISTS IDX_USER_USERNAME
    ON USER_MANAGEMENT.USER(USERNAME);

CREATE INDEX IF NOT EXISTS IDX_USER_EMAIL
    ON USER_MANAGEMENT.USER(EMAIL);

CREATE INDEX IF NOT EXISTS IDX_USER_PHONE_NUMBER
    ON USER_MANAGEMENT.USER(PHONE_NUMBER);

CREATE INDEX IF NOT EXISTS IDX_USER_POSITION_ID
    ON USER_MANAGEMENT.USER(POSITION_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_GOVERNORATE_ID
    ON USER_MANAGEMENT.USER(GOVERNORATE_ID);

-- ==============================================
-- CREATE INDEXES FOR FOLLOWING
-- ==============================================
CREATE INDEX IF NOT EXISTS IDX_FOLLOWING_FOLLOWER_ID
    ON USER_MANAGEMENT.FOLLOWING(FOLLOWER_ID);

CREATE INDEX IF NOT EXISTS IDX_FOLLOWING_FOLLOWED_ID
    ON USER_MANAGEMENT.FOLLOWING(FOLLOWED_ID);

-- ==============================================
-- CREATE INDEXES FOR FOLLOW
-- ==============================================
CREATE INDEX IF NOT EXISTS IDX_FOLLOWING_REQUEST_SENDER_ID
    ON USER_MANAGEMENT.FOLLOWING_REQUEST(SENDER_ID);

CREATE INDEX IF NOT EXISTS IDX_FOLLOWING_REQUEST_RECEIVER_ID
    ON USER_MANAGEMENT.FOLLOWING_REQUEST(RECEIVER_ID);

-- ==============================================
-- CREATE INDEXES FOR USER CREDENTIALS
-- ==============================================
CREATE INDEX IF NOT EXISTS IDX_USER_CREDENTIAL_USER_ID
    ON AUTH.USER_CREDENTIAL(USER_ID);